quanteda/quanteda

R/toLower.R
Use the Unicode upper- and lowercase character categories instead of [A-Z] and [a-z] for matching all uppercase words. That should make keeping acronyms work for all character sets that have upper- and lowercase versions of letters defined in Unicode.
I used the slightly longer but more descriptive identifiers for the Unicode character classes (`\p{Lowercase_Letter}` instead of `\p{Ll}`). I could also amend the code to use the more concise format.
=> Make keeping acronyms in toLower work for non-English words

R/corpus.R
Currently fails on summary(ukManifestos) due to Latin-1 characters in text 49 (UK_natl_1997_en_SEP).
=> Fix non-UTF-8 error in nsentence()

R/textfile.R
Resolves #85 
NB: This does not currently allow data files with different columns or
variable names.
=> Make `textfile` handle multiple structured data files

R/dfm-classes.R, tests/testthat/testDfm.R
In two ways:
- less intermediate shuffling of columns
- directly call Matrix::rbind2 if the columns are identical
This has the behaviour change of no longer returning an ordered list of feature-columns (which will require a version bump, documentation updates, etc.).
Incidentally, this also fixes a bug when rbind is called with a single dfm argument.
Fixes #173
=> Improve performance of rbind.dfm

R/corpus.R, R/textfile.R, tests/testthat/data/fruits1.csv, tests/testthat/data/fruits1.txt, tests/testthat/data/fruits2.csv, tests/testthat/testCorpus.R, tests/testthat/testTextfile.R
Also changes the way corpora are combined to use data.table.
Fixes #131
=> Add support for different docvars in structured text file

R/plots.R, tests/testthat/testPlots.R
Defaults are absolute for single document and relative for multiple documents, but can always be overridden.
=> Make default plot.kwic scale depend on number of documents (fixes #194)

R/dfm.R
Correcting typo "use supplied" -> "user supplied"
=> Correcting typo

R/corpus.R
The corpus function mentions that an integer can be supplied to the `text_field` argument in `corpus`. However, this returns an error where `text_fieldi` is not found. 
The cause of this error is that `text_fieldi` is not created when the `text_field` value is not a character. 
This pull request fixes this bug, checks that if  `text_field` is present that it is length = 1.
=> Fix bug in corpus text_field

R/convert.R, R/dictionaries.R, man/convert-wrappers.Rd, man/convert.Rd, man/dictionary.Rd, tests/data/dictionaries/mary.dic, tests/data/dictionaries/mary.lc3, tests/testthat/test-convert.R, tests/testthat/test-dictionaries.R
Makes it possible to construct a list through dictionary(), without wrapping it in a list().
Adds a validator to the S4 class for dictionary, to ensure that all values are character, and better tests that all keys are supplied (as list names).
Adds constructor tests for dictionary for above conditions, and for file formats.
Also removes the **tm** package from `Imports` by conditioning the examples and the `testthat` tests.
Closes #407
=> Error checking and argument handling for dictionary construction

R/dfm_compress.R, tests/testthat/test_dfm-compress.R
The bug happened when there were documents with zero features, and it tried to recompile the sparse matrix index.  Previously this was fixed for zero-frequency features, but not for zero-frequency documents.
Also added new tests for these conditions.
=> Fixes #467 dfm_compress bug

R/tokens_lookup.R, man/tokens_lookup.Rd, tests/testthat/test-tokens_lookup.R
This is for #500, adding functionality to `tokens_lookup` that apply a dictionary to `tokens` whose multi-word features are already concatenated. Please rename the `multiword` argument to something better.
=> Add multiword argument to solve #500.

src/tokens_select_mt.cpp, tests/testthat/test-corpus-compress.R
Addresses #530. 
Still needs additional work as per #530 on the other three platforms where the failures have to do with C++ code.
See https://cran.r-project.org/web/checks/check_results_quanteda.html.
=> Skip the test on CRAN that is failing for r-devel-windows-ix86+x86_64

NEWS.md, R/dfm.R, R/tokens_lookup.R, man/tokens_lookup.Rd, tests/testthat/test-dfm.R, tests/testthat/test-dfm_lookup.R
Allows `dfm(x, dictionary = something)` where something is a dictionary with multi-word values. This happens by calling `tokens_lookup` before constructing the dfm, if  the dictionary contains any multi-word values. Otherwise it calls `dfm_lookup` internally after compiling the dfm, which is generally faster.
Solves #544.
=> Dfm tokens lookup

NEWS.md, R/RcppExports.R, R/dictionaries-liwc_old.R, tests/data/dictionaries/liwc_extracodes.dic, tests/data/dictionaries/mary_doubleterm.dic, tests/data/dictionaries/mary_missingcat.dic, tests/data/dictionaries/mary_multipletabs.dic, tests/testthat/test-dictionaries.R
Adds robustness for reading improperly formatted LIWC files, and adds tests.
Still need to add tests for the 
These exceptions are handled in e.g. https://github.com/kbenoit/quanteda/blob/master/R/dictionaries-liwc_old.R#L54-L61 but need tests.
=> LIWC robustness additions

R/dfm.R
This is a small revision to compile_dfm.tokens. It seems not necessary to transpose sparseMatrix if sparseMatrix is constructed in this way. Transposing can be costly if a `dfm` is huge.
=> Stop transposing sparseMatrix in compile_dfm.tokens

R/RcppExports.R, src/RcppExports.cpp, src/recompile.h
This branch should eliminate the following warning.
```r
In file included from tokens_select_mt.cpp:3:0:
recompile.h: In function 'bool is_encoded(Rcpp::CharacterVector)':
recompile.h:30:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (std::size_t i = 0; i < types_.size(); i++) {
```
=> Hotfix recompile

src/recompile.h, src/tokens_lookup_mt.cpp
This fixes a bug that `tokens_lookup()` allocates a huge amount of memory when there is no match.
=> Fix bug that allocate huge amount of memory when there is no match

R/RcppExports.R, R/dfm_subset.R, R/dfm_trim.R, man/dfm_subset.Rd, src/RcppExports.cpp, tests/testthat/test-dfm_subset.R
Fixes the reordering of features in `dfm_trim()` - solves #858.
Also implements selection on a dfm for `dfm_subset()`, per discussion here: https://github.com/kbenoit/quanteda/issues/859.
=> Fix reordering of features in dfm_trim

R/RcppExports.R, R/dfm_weight.R, src/RcppExports.cpp, tests/testthat/test-dfm.R, tests/testthat/test-dfm_trim.R, tests/testthat/test-dfm_weight.R
This bug was actually caused by that problem occurring in `docfreq()`, called by `dfm_trim()`. This fixes the problem and adds tests for both `docfreq()` and `dfm_trim()` for this condition.
Fixes #829
=> Fix issue 829, dfm_trim breaking when dfm contains duplicated featnames

R/RcppExports.R, R/textstat_keyness.R, src/RcppExports.cpp, src/init.c
=> Solve unregistered symbol issue

R/RcppExports.R, R/dfm-print.R, R/quanteda-documentation.R, R/tokens.R, man/quanteda-package.Rd, src/RcppExports.cpp, tests/testthat/test-dfm.R
Fixes #871, when dfm.print is called without `package:quanteda` being loaded.
Also adds the skip attribute being set when tokens are created.
=> Fix #871 print.dfm without loading namespace

R/RcppExports.R, R/character-methods.R, R/corpus.R, R/dfm-classes.R, R/dfm-methods.R, R/dfm.R, R/kwic.R, R/quanteda_options.R, R/textstat_readability.R, man/cbind.dfm.Rd, man/quanteda_options.Rd, src/RcppExports.cpp, tests/testthat/test-as.dfm.R, tests/testthat/test-convert.R, tests/testthat/test-dfm.R, tests/testthat/test-dfm_group.R
Adds methods for:
- cbind: dfm + numeric, numeric + dfm, dfm + matrix, matrix + dfm
Adds `quanteda_options`: `docnames_stem` and `featnames_stem` to centralise the sub names for documents and features that are unassigned. (I noticed that what is done in `corpus()` and `dfm()` was different from `as.dfm()`.)
Still needed:
=> Improve cbind functions for dfm and conformable objects

R/wordstem.R, tests/testthat/test-dfm.R, tests/testthat/test-wordstem.R
Fixes #909
```r
txt <- "Tests for developers."
toks <- tokens(txt, remove_separators = FALSE, remove_punct = TRUE)
tokens_wordstem(toks)
```
=> Don't issue an error for wordstem if a character element is *entirely* whitespace

DESCRIPTION, NEWS.md, R/dfm-classes.R, tests/testthat/test-dfm.R
Or more generally, feature names that began with `quanteda_options("base_featname")`.
- Fixes #946
- affected `dfm_select()`
- affected `dfm_lookup()`
=> Fix cbind.dfm problem caused by feature names starting with "feat"

R/corpus_trim.R, man/corpus_trim.Rd
Keeps `corpus_trim()` and the already internal `corpus_trimsentences()` but makes the former internal as well.
=> Make corpus_trim() internal only

R/tokens_lookup.R, tests/testthat/test-tokens_lookup.R
```r
toks <- tokens("The shape of the car is not good, but the color is nice.") # neutral sentence
tokens_lookup(toks, dictionary = data_dictionary_LSD2015, exclusive = FALSE)
tokens from 1 document.
text1 :
[1] "The"          "shape"        "of"           "the"          "car"          "is"           "NEG_POSITIVE" "POSITIVE"     ","           
[10] "but"          "the"          "color"        "is"           "POSITIVE"     "."    
```
=> Drop unused keys to solve a bug found in #1011

src/sequences_mt_.cpp, tests/testthat/test-textstat_collocations.R
I notice that `textstat_collocations` stops and crashes in a infinite loop when at least one document is shorter than `size`. This is critical.
=> Hotfix collocation

R/regex2fixed.R, tests/testthat/test-regex2fixed.R
Regex special characters are escaped by utils::lob2rx
=> Remove excape_regex

R/convert.R, R/dfm_weight.R, tests/testthat/test-convert.R, tests/testthat/test-dfm_weight.R
- Solves #1091 
- Now correctly records weight (and other) attributes after `tfidf()`.
=> Issue error for converting weighted dfm to a topic model format

src/quanteda.h, tests/testthat/test-phrases.R, tests/testthat/test-textmodel_wordfish.R, tests/testthat/test-textstat_collocations.R
I was investigating #1003 and #1200. `rhub::check_with_sanitizers()` indicated the bit shift in our hash function is causing an error. See line 6221 (or search for 'runtime error') in https://builder.r-hub.io/status/original/quanteda_1.0.0.tar.gz-9672f200479b4108a6308a4d54edcc09. The log looks very different but the location of the error is very close to the TBB error in the [CRAN UBSAN check](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/quanteda/quanteda-Ex.Rout). 
After modifying the hash function, the runtime error has disappeared from check. I hope the same thing to happen in CRAN check.
=> Check ubsan

R/dfm-methods.R
Per https://github.com/quanteda/quanteda/issues/1222
Could not run `devtools::document()` w/o error...and thus run CRAN checks...likely because of the C level coding which I have no experience in yet (or because of running the make command on a Windows machine that doesn't have it installed):
```
> devtools::document()
Updating quanteda documentation
Loading quanteda
Re-compiling quanteda
"C:/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
"C:\Users\Tyler\GitHub\quanteda" --library="C:\Users\Tyler\AppData\Local\Temp\RtmpgtkuNn\devtools_install_25b82acc71fe"  \
--no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec --no-multiarch --no-test-load --preclean 
* installing *source* package 'quanteda' ...
** libs …
```
=> added DocumentTermMatrix and TermDocumentMatrix mathos for the generic as.dfm

NEWS.md, R/textmodel_wordscores.R, man/predict.textmodel_wordscores.Rd, man/textmodel_wordscores.Rd, tests/testthat/test-textmodel_wordscores.R
Following the discussion in #1229, I added the option `include_reftexts` to `predict.textmodel_wordscores()` which has `TRUE` as the default.
=> Issue 1229

R/corpus.R, tests/testthat/test-corpus.R
To make corpus.data.frame() work with tibbles, grouped data.frames, etc.
Closes #1232.
=> Fix #1232 corpus() for dplyr grouped data.frame objects

R/dfm-classes.R, man/as.matrix.dfm.Rd, tests/testthat/test-as.dfm.R, tests/testthat/test-textstat_keyness.R
Makes default the creation of a column called "document" and drops the rownames.
Solves #1212.
From `devtools::revdep_check()`:
```r
Checked politeness    : 1 error  | 0 warnings | 0 notes
```
Needs to be investigated.
New behaviour:
```r
as.data.frame(data_dfm_lbgexample[, 1:15])
```
=> Improve as.data.frame.dfm() method

R/zzz.R
Advertise our website in the start up message.
```
Initializing package: ‘quanteda‘
Package version: 1.0.5
Parallel computing: 3 of 4 threads
To learn how to use ‘quanteda‘ through examples and tutorials, go to https://quanteda.io/
Attaching package: ‘quanteda’
The following object is masked from ‘package:utils’:
View
```
=> Add link to package website in startup message

R/dfm-classes.R, man/as.matrix.dfm.Rd, tests/testthat/test-as.dfm.R
Default handling of featnames in as.data.frame.dfm() is now to set `check.names = FALSE` to prevent adjustment of syntactically invalid variable names.
=> Solves #1245

DESCRIPTION, NEWS.md, R/dfm_trim.R, R/dfm_weight.R, tests/testthat/test-dfm_trim.R, tests/testthat/test-dfm_weight.R
- fixes docfreq() to work even for weighted dfm objects.
- adds warning for leaving min_count default at 1 when using fractional docfreq values
- improves stability.
Addresses #1237.
Still leaves some behaviours that may be unexpected by some users, when trimming a weighted dfm with fractional values, or supplying partially fractional values as arguments. Related to #1181.
=> Improve stability of dfm_trim()

R/fcm-methods.R, R/fcm.R, man/fcm-class.Rd, tests/testthat/test-fcm.R, tests/testthat/test-fcm_methods.R
Adds extra `margin` slot to record original frequency for #1262. I though fcm methods should change its value, but no longer think so, because names in the vector can be matched with features of the fcm when it is used in upcoming `fcm_weight()` etc. I was not sure what should happen when `fcm_lower()` is applied to the fcm, so made it to do nothing.
=> Add original frequency to a fcm

DESCRIPTION, NEWS.md, R/textstat_dist.R, R/textstat_simil.R, man/textstat_simil.Rd, tests/testthat/test-textstat_dist.R, tests/testthat/test-textstat_simil.R
Solves #1266.
Improves the consistency of the `selection` argument by enforcing it to be a valid index on the dfm dimension defined in `margin`. 
Also fixes a bug in `as.list.dist_selection()` that caused all but the first column (of the non-symmetric matrix) to be dropped, resulting in a list of length 1.
=> Improve consistency of selection argument for textstat_dist/simil()

R/corpus-methods-base.R, tests/testthat/test-corpus.R
This is a very minor edit of `+.corpus`. Originally it used `rbind` in base-R and I changed it to `data.table::rbindlist` so that it can combine two corpus objects with different lists of docvars. As it uses data.table function, this supposedly combines faster. I tested with both normal (i.e. not compressed) corpus objects and compressed corpus objects, and it worked fine.
=> use data.table functions for corpus addition

R/corpus.R, man/corpus.Rd, man/quanteda-package.Rd, tests/testthat/test-corpus.R, tests/testthat/test-summary.R
- Simplify code in `corpus.data.frame()`
- Make `"doc_id"` the default `docfield_id`
- Use `row.names(x)` if `docfield_id` not found
- Use quanteda default if `docfield_id` not found and rownames are not set
- Solves #1293
=> Improve `corpus.data.frame()`

R/dfm_trim.R, man/dfm_trim.Rd, man/quanteda-package.Rd, tests/testthat/test-dfm_trim.R
- Add warnings of fractional termfreq
- Correct generic signiture
Note that `dfm_trim()` should warn only when x@weightTf$scheme == "count" but we cannot condition until #1274 has been solved.
=> Address #1254

R/tokens.R, tests/testthat/test-tokens.R
Indexing error message is nicer and the same as for `dfm()`.
=> Make error message more friendly

R/data-documentation.R, man/data_dictionary_LSD2015.Rd
- Fix mistake: "neg_negative" was called "negative" in the documentation
- Add example on how to use tokens_compound() before creating a dfm object to take into consideration the neg_negative/neg_positive tokens combinations
- Rebuild man
=> Fix and extend documentation of data_dictionary_LSD2015

R/textmodel_lsa.R
Avoid errors in SVD in a certain condition.
```
Error in UseMethod("svds") : 
no applicable method for 'svds' applied to an object of class "dfm"
```
=> Coerce to dgCMatrix before SVD

DESCRIPTION, NEWS.md, R/dfm_lookup.R, src/tokens_lookup_mt.cpp, tests/testthat/test-dfm_lookup.R, tests/testthat/test-tokens_lookup.R
- It happens when there are keys that does not appear in dictionary and nomatch is used
- Solve by changing how to obtain a new key ID
- Probably a regression induced when #1278 was solved
=> Fix incorrect key ID given for no-match #1347

tests/testthat/test-textplot.R
Issue #1357 
This is to resolve the compatibility issue of `quanteda` with a new version of `ggplot2` which has a different internal object structure. I believe the compatibility issue only arises for tests. I checked with `ggplot2` v2.2.1.9000, which is the pre-release of 2.3.
=> Compatibility for ggplot2 v2.3

R/textstat_frequency.R
the dfm needs to be grouped before weighting, otherwise textstat_frequency() sums up the weights (here: proportions) for the 2 obama and 2 bush speeches.
current help file:
```r
> # plot relative frequencies by group
> dfm_weight_pres <- data_corpus_inaugural %>%
+     corpus_subset(Year > 2000) %>%
+     dfm(remove = stopwords("english"), remove_punct = TRUE) %>%
+     dfm_weight(scheme = "prop")
> 
> # calculate relative frequency by president
> freq_weight <- textstat_frequency(dfm_weight_pres, n = 10,
+                                   groups = "President")
> freq_weight
feature   frequency rank docfreq group
1    freedom 0.030392921    1       2  Bush
2    america 0.021731459    2       2  Bush
3    country 0.019164510    3       2  Bush
4     nation 0.018849615    4       2  Bush
5 …
```
=> correct minor error in documentation

NEWS.md, R/textstat_readability.R, docs/reference/textstat_readability.html, man/textstat_readability.Rd, tests/data_creation/create_wordlists.R, tests/testthat/test-textstat_readability.R
Adds an argument to `textstat_readability()` that I need for the replication materials to work, for a forthcoming article in the _AJPS_ , "Measuring and Explaining Political Sophistication Through Textual
Complexity", deposited at https://doi.org/10.7910/DVN/9SF3TI.
=> Integrate sophistication

R/textmodel_wordscores.R, R/textplot_scale1d.R, man/textmodel_wordscores.Rd, man/textplot_scale1d.Rd
- Correct syntax in `textmodel_wordscores()` man
- Use `ie_dfm` for the Wordfish example in `textplot_scale1d()` to match the structure with the Wordscores and CA examples
=> Minor corrections in documentation of textmodel_wordscores() and textplot_scale1d()

NEWS.md, R/dfm_compress.R, R/dfm_group.R, tests/testthat/test-dfm_compress.R
Fixes #1506.
`group_dfm()` when applied to features returned docvars but not "metadoc" such as `_document`. This fix ensures that it does.
- plus some linting improvements
- added tests for #1506
- updated NEWS
=> return metadoc as well as docvars from group_dfm()

tests/testthat/test-corpus.R
Fixes #1534 
For compliance with soon-to-be-released 0.80 CRAN update of **dplyr**.
=> Add explicit prefix for dplyr::n() verb

R/dfm.R, R/dimnames.R, tests/testthat/test-dfm.R, tests/testthat/test-fcm.R
On some Windows systems, dimnames are not encoded.
=> Fix encoding

R/textstat_keyness.R
Hi once again @kbenoit! This is a very minor PR mostly intended to inform you that, after a long time on other stuff (i.e., my day job), I'm once again on a side project using `quanteda`. We (myself and @fjensz) are developing a package for intended ROpenSci submission which bundles a bunch of `quanteda` and `topicmodels` tools into meta-functions for the analysis of temporally structured text collections (such as collections of historical reports). The key aspects of interest in these are temporal patterns, and so standard `keyness` and `topicmodels` results are mapped onto time, and results presented in interactive visualisations to allow time series to be plotted, with word associations or topics displayed on hover. (People who need this generally resort to commercial software because …
=> fix textstat_keyness when only 2 docs with same name

R/docnames.R, man/docnames.Rd, tests/testthat/test-docnames.R
Fixes #1574 by coercing all assigned docvars to `character`.
=> Coerce all assigned docvars to character

R/dfm-methods.R, R/dimnames.R, R/textstat_simil.R, tests/testthat/test-docnames.R, tests/testthat/test-textstat_dist_old.R
Found a few more places where we should coerce the elements of `dfmat@Dimnames` to `character`. 
I even wrote an S4 validator function but that doesn't work since in dfm.R you are now creating the dfm without dimnames, and then setting them separately. And the class validators are not invoked with low-level manipulations anyway, so it's not a robust solution.
Anyway take a look at these latest additions.
=> More fixes to 1574

R/textstat_readability.R, man/textstat_readability.Rd
Fixes #1593. Amends the JSTOR reference url for Klare (1975) in textstat_readability.
=> Fix reference url for Klare (1975) in textstat_readability

DESCRIPTION, NEWS.md, R/docvars.R, tests/testthat/test-docvars.R
- fixes names(docvars())<- to solve #1603
- linting changes for docvars.R
- ensures V1, V2, ... names for docvars without names (vectors)
@koheiw I know this will be solved in `dev-corpus2` (and provides yet one more good reason to move to that structure) but this provides a fix in the meantime. Ain't pretty but it works.
=> Fix docvar addressing for corpus

NEWS.md, tests/testthat/test-tokens.R
Fixes #1604, mainly by removing the strange whitespace variant from the test, which was "em-space" \u2003. Not like we encounter these every day.
Tested on Ubuntu 18.10.
=> Remove em-space, fixes #1604

R/fcm.R, R/textstat_dist_old.R, R/textstat_keyness.R, R/textstat_readability.R, man/fcm.Rd, man/textstat_readability.Rd, man/textstat_simil_old.Rd, tests/testthat/test-as.dfm.R
- Fixes some problems seen at https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/quanteda-00check.html
- Skips (on CRAN) some failing tests related to dfm dimension name element encoding
=> Replace em dash hyphens with simple hyphen

DESCRIPTION, NEWS.md, R/textstat_frequency.R, man/textstat_frequency.Rd, tests/testthat/test-textstat_frequency.R
Fixes #1646 by allowing `force = TRUE` to be passed to `dfm_group()` via `...` in `textstat_frequency()`.
However note that it is now possible to have a group with no "frequency":
``` r
library("quanteda")
dfmat <- dfm(c("a", "a b", "a c")) %>%
dfm_tfidf()
dfmat
tstat <- textstat_frequency(dfmat, groups = c(1, 2, 2), force = TRUE)
tstat
str(tstat)
```
We could filter out the zero-frequency features, but keep at least one feature per group, or we could just leave it as is, even if this looks strange. The user "used the force" so maybe we just consider that it's on the user's head?
=> Add ... to textstat_frequency to pass to dfm_group

src/tokens_chunk_mt.cpp
I remember that we had similar issue in `tokens_select_mt.cpp` etc. earlier.
=> Cast to double to address #1653

R/corpus.R, man/corpus.Rd
Changes 
> the text of the document is a variable identified by \code{textid_field};
to
> the text of the document is a variable identified by \code{text_field};
=> Fix typo in corpus documentation

appveyor.yml
Just changing R version for appveyor CI from 3.5.2 to 3.5.3
=> Tick up R-version for Appveyor CI

R/tokens.R, tests/testthat/test-tokens.R
0 is reserved for pads and needs to be protected when combining separate tokens indexes.
=> Fix #1695 `+.tokens` with pads

NEWS.md, R/corpus_sample.R, R/utils.R, man/corpus_sample.Rd, man/sample_bygroup.Rd, tests/testthat/test-bootstrap.R, tests/testthat/test-corpus_sample.R, tests/testthat/test-dfm_sample.R, tests/testthat/test-utils.R
This affects `corpus_sample()` primarily, but also fixes an unforeseen bug from `sample_bygroup()` caused by the unfortunate way `base::sample()` is written, so that `sample(1:2)` is the same as `sample(2)`.
The new behaviour is very useful if we want to say sample documents from a large set for machine learning, e.g. to choose half of the documents in the 2000-text `data_corpus_movies`, we could use:
```r
> corpus_sample(data_corpus_movies, size = 500, by = "Sentiment") %>%
+     docvars("Sentiment") %>%
+     table()
.
neg pos 
500 500
> corpus_sample(data_corpus_movies, size = c(10, 20), by = "Sentiment") %>%
+     docvars("Sentiment") %>%
+     table()
.
neg pos 
10  20  
```
=> Add size control for sampling by group

R/dfm_group.R, R/docnames.R, tests/testthat/test-dfm_group.R
#1632. I needed to catch errors caused by inconsistency in docvars in current version in `docid()`, but can be better in v2.0.
=> Issue 1632

tests/testthat/test-as.dictionary.R
Fixes breaking tests in `test-as.dictionary.R` relating to changes in the sentiment dictionaries included with **tidytext**.
Fixes #1705
=> Fix #1705 relating to tidytext dictionary changes

NEWS.md, R/textstat_simil.R, tests/testthat/test-textstat_simil.R
There was disagreement between `textstat_simil()` and `proxyC::simil()` in classing symmetric outputs. This bug could cause not only misleading result but also nasty crash.
=> Fix a bug in classing symmetric matrices

R/dfm_group.R, R/docvars.R, R/tokens_segment.R, R/utils.R, tests/testthat/test-docvars.R, tests/testthat/test-tokens_segment.R
I do not want to spend time to fix to relatively new bug #1734, so just disallowed assigning a vector (we do not need this functionality anyway). `docvars` is a mess. We should switch to v2.0 soon.
=> Fix docvar assignment inconsistency

NEWS.md, R/convert.R, man/convert-wrappers.Rd, man/convert.Rd, tests/testthat/test-convert.R
Adds `omit_empty = TRUE` to `convert()`, but this is only active for the "topicmodels" and "lda" formats. It is forced to be TRUE for "stm", and is inactive (equivalent to "FALSE") for everything else.
It might make more sense to make the default 
```
omit_empty = ifelse(!to %in% c("stm", "topicmodels", "lda"), FALSE, TRUE) 
```
Fixes #1660.
=> Add omit_empty to convert()

R/casechange-functions.R, man/char_tolower.Rd, man/dfm_tolower.Rd, man/tokens_tolower.Rd
Only `locale` was passed through the case change functions, and this was inconsistently applied. Better to remove the unnecessary ellipsis entirely.
Fixes #1710
=> Remove ... from case change functions

R/textstat_lexdiv.R, man/textstat_lexdiv.Rd, tests/testthat/test-textstat_lexdiv.R
Yule's I is another textual diversity measure. Although it is similar to Yule'K, it is not the same. It has recently been used in the article by Tolochko & Boomgaarden (2019).
Tolochko, P., & Boomgaarden, H. G. (2019). Determining Political Text Complexity: Conceptualizations, Measurements, and Application. International Journal of Communication, 13, 21.
=> Add Yule's I to textstat_lexdiv()

R/textplot_wordcloud.R, tests/testthat/test-textplot.R
When no features remain after the default trimming, `textplot_wordcloud()` should halt with an error rather than produce the behaviour shown in #1755.
=> Fix #1755 - add error for empty wordcloud

src/tokens_lookup_mt.cpp, tests/testthat/test-tokens_lookup.R
Further  fix for #1743. Let's marge this before #1772 so that I can marge this to v2.
=> Fix ID shifting of paddings in document without keyword values

R/corpus-methods-base.R
Former `summary.corpus()` behaviour restored, now gets the total n before the `head()` truncates the document vector.
Fixes #1785
=> Fix total document report n

R/corpus-methods-quanteda.R, R/meta.R, tests/testthat.R, tests/testthat/test-corpus.R, tests/testthat/test-textstat_simil.R
Formerly, the user metadata was not copied for pre-v2 corpora. In addition, the corpus creation date (field `created`) was not correctly set (as a date object).
Fixes #1799
=> Fix as.corpus() handling of user metadata for pre-v2 corpora

R/corpus-methods-base.R, tests/testthat/test-corpus.R
- Fixes an error where the remaining document message was triggered even when there were no document-specific items printed.
- Increases the stringency of tests to include the entire output, not just a fixed match on the first part of the output.  (This is why we did not catch this error to begin with.)
=> Fix printing error for corpus summary

R/dfm_group.R, R/docvars.R, man/dfm_group.Rd
Improve efficiency of grouping by skipping system variables. Currently, `group_docvars()` checks all the document variables including including system variables, which must not be dropped in any case.
=> Improve efficiency of grouping by skipping system variables

tests/testthat/test-fcm.R, vignettes/pkgdown/replication/text2vec.Rmd
- Fixes and re-enables test for `text2vec::tcm()` and `fcm()` equivalence. Thanks  @dselivanov for the correction in https://github.com/dselivanov/text2vec/issues/313.
- Fixes the text2vec replication vignette to reflect changes to the **text2vec** and **rsparse** packages. Closes #1825.
@dselivanov Interestingly our replication got better results than your original vignette. I suspect this is because we leave in ghost "pads" for words removed, which `prune_vocabulary()` may not do. This seems to improve the local context weights because it preserves original word distances. `fcm()` also never spans sentences.
```r
> berlin <- word_vectors["paris", , drop = FALSE] -
+   word_vectors["france", , drop = FALSE] +
+   word_vectors["germany", , drop = FALSE]
> cos_sim <- textstat_simil(x = …
```
=> Fix word2vec test and example

R/tokens.R, cran-comments.md, tests/testthat/test-tokens.R
Necessary because otherwise it breaks **clustRcompaR**, which passes this through in `cluster(..., remove_twitter = FALSE)`.
Now works so that it issues a deprecation warning, but implements the old functionality for `remove_twitter = FALSE` by changing the tokenizer type to "word1". So in this PR:
```r
> tokens("@username #hashtag test.", remove_twitter = FALSE)
Tokens consisting of 1 document.
text1 :
[1] "@username" "#hashtag"  "test"      "."        
Warning message:
'remove_twitter' is deprecated; for FALSE, use 'what = "word2"' instead. 
> tokens(tokens("@username #hashtag test."), remove_twitter = FALSE)
Tokens consisting of 1 document.
text1 :
[1] "@"        "username" "#"        "hashtag"  "test"     "."       
Warning message:
'remove_twitter' is deprecated and inactive for …
```
=> Restore remove_twitter to deprecated rather than defunct status

R/tokens.R, tests/testthat/test-tokens.R
#1882 is probably due to the change in how ICU handles separators. Even if there are other issues, we have to be ready for the change anyway.
=> Change the handling of separators per ICU 36

R/convert.R, tests/testthat/test-corpus_reshape.R, tests/testthat/test-tokens_segment.R
These are caused by a change to the default in data.frame in the next major R release, in which `stringsAsFactors = FALSE` by default.
This fixes the tests by forcing factors, but also cleans up something else that was happening with `dfm2lsa()`. I think this was **lsa**'s problem, not ours. In any case, I fixed it by using the `lsa::as.textmatrix()` converter instead of re-engineering it. We could avoid the conversion to dense matrix and back by re-engineering the conversion ourselves, but I will leave this for future work.
Solves #1901.
=> Fix test errors for r-devel

R/dfm.R, tests/testthat/test-corpus.R, tests/testthat/test-dfm.R, tests/testthat/test-docvars.R, tests/testthat/test-textplot.R, tests/testthat/test-textplot_network.R
I decided to fill in some of the gaps in our code coverage. Not surprisingly, this revealed a few inconsistencies, which I fixed. Example: the verbose report for `dfm.tokens(x, stem = TRUE)`, which unlike the same option for `dfm.dfm()`, did not take the default dictionary from quanteda_options.
I also removed (or commented out) some functions that were untested, because they are no longer used.
=> Increase codecov

DESCRIPTION, NEWS.md, R/tokenizers.R, man/data-internal.Rd, man/data_char_sampletext.Rd, man/data_char_ukimmig2010.Rd, man/data_corpus_inaugural.Rd, man/data_dfm_lbgexample.Rd, man/data_dictionary_LSD2015.Rd
This PR is do address the [huge slowdown](https://stackoverflow.com/questions/60987472/building-document-feature-matrix-quanteda-with-twitter-data-takes-only-a-few-m) caused by the functions to preserve and restore URLs and tags. 
It was taking over 500 sec to tokenize 100k twitter posts, but it becomes 10 sec for 100k and 100 sec for 1m with this patch. 
```
> microbenchmark::microbenchmark(
+     "10k" = tokens(head(corp$text, 10000)),
+     "100k" = tokens(head(corp$text, 100000)),
+     "1m" = tokens(head(corp$text, 1000000)),
+     times = 5, unit = "s"
+ )
Unit: seconds
expr        min         lq      mean      median          uq       max neval
10k  0.8025744  0.8268469  1.001053   0.8357416   0.8714707   1.66863     5
100k  7.0850760  9.3038414  9.273580   9.4945126  10.1048823 …
```
=> Fix special

NEWS.md, R/quanteda_options.R, R/tokenizers.R, inst/WORDLIST, man/quanteda_options.Rd, tests/testthat/test-tokens.R, tests/testthat/test-tokens_segment.R
Exploiting the faster hashtag substitution mechanism, this PR improves tokenization of CJK Twitter posts. 
In the master branch:
```r
> txt <- "オリンピック延期決定！ #政治 #安部政権"
> tokens(txt)
Tokens consisting of 1 document.
text1 :
[1] "オリンピック" "延期"         "決定"         "！"           "#"            "政治"        
[7] "#"            "安部"         "政権" 
```
In this branch:
```r
> txt <- "オリンピック延期決定！ #政治 #安部政権"
> tokens(txt)
Tokens consisting of 1 document.
text1 :
[1] "オリンピック" "延期"         "決定"         "！"           "#政治"        "#安部政権"   
```
There is no performance change (or slight improvement).
Comparison with `word1`
```
Unit: seconds
expr       min        lq      mean    median        uq       max neval
10k  1.058817  1.085394  1.180548  1.130297  1.252658  1.375576     5
100k 10.406045 11.509046 …
```
=> Dev non ascii tags

R/tokens.R, man/tokens.Rd, tests/testthat/test-tokens.R
Make `remove_twitter` defunct with a warning, and make it non-operational, but generating a warning instead of an error. Also improves the documentation to explain this better.
Solves #1932.
=> Defunct remove_twitter and explain better in tokens.Rd

R/corpus.R
When the texts were vectors rather than single character elements, then `corpus.Corpus()` read them in as individual elements.  This fixes that by concatenating the vectors of documents as paragraphs, separated by two `\n` characters.
This was causing a problem on a Factiva source import, for instance.
=> Fixes tm VCorpus corpus constructor problem

NEWS.md, R/dfm_lookup.R, tests/testthat/test-dfm_lookup.R, tests/testthat/test-tokens_lookup.R
This is a major bug. `dfm_lookup()` returns a dfm without columns when there is no matches.
```r
> toks <- tokens(c("aaaa aaaa", "bbbb"))
> dfmt <- dfm(toks)
> dfm(tokens_lookup(toks, dict)) # Correct
Document-feature matrix of: 2 documents, 2 features (100.0% sparse).
features
docs    key1 key2
text1    0    0
text2    0    0
> dfm_lookup(dfmt, dict) # Not (not features)
Document-feature matrix of: 2 documents, 0 features.
```
=> Ensure dfm_lookup returns dfm with all the keys

R/RcppExports.R, R/tokens_select.R, man/tokens_select.Rd, src/RcppExports.cpp, src/tokens_select_mt.cpp, tests/testthat/test-tokens_select.R
This PR upgrades `tokens_select()` to allow `startpos` and `endpos` to be a vector. We can create KWIC view with this function. For example,
``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 2.0.2
#> Parallel computing: 2 of 4 threads used.
#> See https://quanteda.io for tutorials and examples.
#> 
#> Attaching package: 'quanteda'
#> The following object is masked from 'package:utils':
#> 
#>     View
toks <- tokens(data_char_ukimmig2010)
kw <- kwic(toks, "migra*")[,c("docname", "from", "to")]
head(kw)
#>        docname from  to
#> 1    Coalition   74  74
#> 2 Conservative   86  86
#> 3 Conservative  134 134
#> 4       Greens    3   3
#> 5       Greens  160 160
#> 6       Greens  374 374
tokens_select(toks[kw$docname], startpos = kw$from, endpos = kw$to)
#> …
```
=> Allow startpos and endpos to be a vector

R/RcppExports.R, inst/include/lib.h, src/RcppExports.cpp, src/collocations_mt_.cpp, src/kwic_mt.cpp, src/tokens_compound_mt.cpp, src/tokens_lookup_mt.cpp, src/tokens_replace_mt.cpp, src/utility.cpp, tests/testthat/test-utils.R
Add interface to change max_load_factor. It is a setting of the hash table that affects performance of C++ functions. 
```r
quanteda:::qatd_cpp_set_load_factor("pattern", 0.025)
quanteda:::qatd_cpp_get_load_factor()
```
We will not export these functions, but they allow us to find optimal settings on different systems with different data.
=> Add interface to set hash table sizes

R/dfm.R, tests/testthat/test-dfm_match.R
In https://github.com/koheiw/newsmap/issues/39, I noticed that `dfm_match()` crashes when `features` contain "". 
```r
toks <- tokens("a b !", padding = TRUE, remove_punct = TRUE)
dfmt <- dfm(toks)
dfm_match(dfm("a b c"), "") # error
```
The root cause is actually `[.dfm`
```
dfmt[,""] #  error
dfm_select(dfmt, "") # works
```
This is a deeper issue that requires careful redesigning of how we handle paddings, because R treats empty names as a special case according to `?names()`:
> The name "" is special: it is used to indicate that there is no name associated with an element of a (atomic or generic) vector. Subscripting by "" will match nothing (not even elements which have no name).
=> Make dfm_match() work with padding

DESCRIPTION, NEWS.md, R/dfm_weight.R, man/dfm_weight.Rd, tests/testthat/test-dfm_weight.R
Adds new scheme for weighting, which is log(x + smoothing), needed for the logit scaling of sentiment (in #1958).
=> Add logsmooth, needed for sentiment

NEWS.md, R/corpus.R, R/dfm.R, R/quanteda_options.R, R/tokenizers.R, R/tokens.R, man/quanteda_options.Rd, tests/testthat/test-corpus.R, tests/testthat/test-dfm.R, tests/testthat/test-tokens.R
This is for restructuring of tokens internals to increase the efficiency with very large corpora.
- Concentrate slow functions within a `lapply()` loop (which can be replaced by `future_lapply()`) (#1965)
- Change how tokenization progress is displayed
- Move character normalization (e.g. hyphens) to tokenizer
- Fix handling of the `verbose` option in `tokens.tokens()` (#1926)
The internal design is tested in `tokens_parallel()` in [a separate branch](https://github.com/quanteda/quanteda/blob/dev-tokens_parallel/R/tokens_parallel.R) and worked with a corpus of 30 million texts (20GB) (takes only 30 min in serial process).
Remaining questions are
- How to print the progress when `verbose = TRUE`?
- When should be switch to `future_lapply()`?
=> Optimize tokenization loop for very large corpora

R/corpus.R, tests/testthat/test-corpus.R
For #1969. I though we will remove NA documents, but it changing the number of documents affect other inputs like `docnames`, `docvars`, so this would be the safest approach.
=> Raise warning for NA

DESCRIPTION, NEWS.md, R/corpus_reshape.R, R/corpus_segment.R, R/quanteda_options.R, R/tokenizers.R, man/quanteda_options.Rd, tests/testthat/test-corpus_reshape.R, tests/testthat/test-nfunctions.R
Address multiple issues related to `corpus_reshape()`
- Stop removing empty documents (#1978)
- Expose stringi's `locale` option (#1979)
- Allow further reshaping segmented corpus
=> Fix corpus_reshape()

DESCRIPTION, R/dictionaries.R, tests/testthat/test-dictionaries.R
Fixes this problem:
```r
> print(data_dictionary_LSD2015, 0, 0)
Dictionary object with 4 key entries.
NULL
```
In the fix, it does not show the `NULL` which is returned by the early return of the function in `print_dictionary()`.
=> Fix dictionary printing problem when max_nkey = 0,  max_nval = 0

NEWS.md, R/dfm.R, man/dfm.Rd, tests/testthat/test-corpus.R, tests/testthat/test-kwic.R, tests/testthat/test-tokens.R
Removes the examples from the dfm help that still contain the `ngrams` argument, despite this being removed many versions ago.
Solves #1990 
Closes #1896 
See also #1602
=> Remove ngrams argument examples from dfm help

R/kwic.R, tests/testthat/test-kwic.R
=> Address #2008

R/zzz.R
to make trouble shooting easier and make users aware of the differences. It also helps to address https://github.com/quanteda/quanteda.textstats/issues/24.
=> Print Unicode and ICU versions

DESCRIPTION, R/convert.R, R/utils.R, man/pattern2list.Rd
These happened even when the argument was not supplied, because `check_logical()` created a value even when this value was missing.
=> Stop omit_empty warnings

R/dfm_match.R, tests/testthat/test-dfm_match.R
`dfm_match()` did not have minimum length of `features`, so set it to 0. This is why https://github.com/koheiw/LSX/pull/47 was breaking many tests.
=> Correct input validation in dfm_match()

R/corpus_segment.R, tests/testthat/test-corpus_reshape.R, tests/testthat/test-corpus_segment.R
Using recently added `drop_docid = FALSE`, stop `corpus_reshape()` and `corpus_segment()` to forget original documents. It should solve #1978.
=> Issue 1978

NEWS.md, R/corpus_trim.R, R/docvars.R, man/as.data.frame.dfm.Rd, src/RcppExports.cpp, tests/testthat/test-docnames.R, tests/testthat/test-docvars.R
Address #2127 by updating `segid_` only when subsetting indices are duplicated. There are other ways (e.g. allowing duplicated docnames) to solve the bug, but  this is the most conservative approach.
```r
> corp[c("1789-Washington.2", "1789-Washington.3")]
Corpus consisting of 2 documents and 4 docvars.
1789-Washington.2 :
"On the one hand, I was summoned by my Country, whose voice I..."
1789-Washington.3 :
"On the other hand, the magnitude and difficulty of the trust..."
> corp[c("1789-Washington.2", "1789-Washington.2")]
Corpus consisting of 2 documents and 4 docvars.
1789-Washington.1 :
"On the one hand, I was summoned by my Country, whose voice I..."
1789-Washington.2 :
"On the one hand, I was summoned by my Country, whose voice I..."
```
=> Issue 2127

R/tokens_compound.R, src/RcppExports.cpp
to make pattern matching more efficient. Address (#2130).
=> Keep unigrams only when window is used

R/corpus-methods.R, R/corpus_reshape.R, R/dfm-subsetting.R, R/docvars.R, R/tokens-methods.R, man/reshape_docvars.Rd, tests/testthat/test-docnames.R, tests/testthat/test-docvars.R
In #2128, `reshape_docvars()` assigns sequential values to `segid_` when duplicated indices are found. This PR improves that by generating unique `segid_` that preserve the original order. This is useful, for example, when users want to sort the documents in original order.
=> Imporve segid generation

R/dictionaries.R, R/pattern2fixed.R, man/convert.Rd, man/unlist_character.Rd, tests/testthat/test-as.dictionary.R, tests/testthat/test-dictionaries.R
```r
> dictionary(list(A = "a", 
+                 B = list(), 
+                 C = character()))
Error in check_entries(dict) : 
Non-character entries found in dictionary key 'B'
```
but it does not error if you apply this patch.
=> Fix bug induced by #2161

R/dictionaries.R, tests/testthat/test-dictionaries.R
Fix a bug induced in the recent update in `merge_dictionary_values()`.
=> Fix merge_dictionary_values()

NEWS.md, R/tokens_chunk.R, tests/testthat/test-tokens_chunk.R
Fix a bug in `tokens_chunk()` that drops docid of empty documents. This leads to unexpected behavior of `tokens_group()` and `dfm_group()`.
=> Fix tokens chunk

inst/include/lib.h
The segfault error below has disappeared from LSX test results soon after notification by the CRAN team.
```
*** caught segfault ***
address (nil), cause 'unknown'
Error in qatd_cpp_fcm(x, length(type), weights, boolean, ordered) : 
value of 'SET_ATTRIB' must be a pairlist or NULL, not a 'symbol'
Calls: fcm -> fcm.tokens -> qatd_cpp_fcm
Execution halted
*** caught segfault ***
address (nil), cause 'unknown'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
Running ‘testthat.R’ [128s/126s]
```
I suspect that it is related to how sparse matrices are created in C++ for `fcm()`. This is where the error is raised by [base R](http://mtweb.cs.ucl.ac.uk/mus/bin/install_R/R-3.1.1/src/main …
=> Set NULL to dimnanes in C++

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/convert.R, R/dfm-classes.R, R/dfm-methods.R, R/dfm.R, R/dfm_group.R, R/dfm_weight.R, R/fcm-methods.R, R/fcm.R, R/object-builder.R, cran-comments.md, inst/WORDLIST, man/dfm-class.Rd, man/dfm.Rd, man/dfm_compress.Rd, tests/testthat.R, tests/testthat/test-fcm_methods.R
- fixes deprecated `as()` calls (mostly `as(., "dgCMatrix")` which we'd used a lot)
- turns on errors for using deprecated versions using `options(Matrix.warnDeprecatedCoerce = 2)` in `testthat.R`
- works for forthcoming Matrix 1.4.2 release (tested from r-forge installation)
=> Fixes for deprecated Matrix calls and for forthcoming Matrix 1.4-2

DESCRIPTION, tests/testthat/test-convert.R
I had to make two changes due to a new CRAN policy of being stricter with packages that are Suggested.
I moved **jsonlite** from Suggests to Imports. It has no imports (since it's one of Jeroen's packages) so doesn't bloat the package. We also need this as a core functionality because of how we are exporting items to JSON to get them to work with pytorch. But @koheiw I wanted to make sure you're ok with it.
I added this to my .Renviron to make this part of all future testing:
```
_R_CHECK_DEPENDS_ONLY_=true
```
The message from CRAN today (although I'd just passed all tests on their own systems! `devtools::check_win_devel()` etc)
```
Thanks, we see when
set _R_CHECK_DEPENDS_ONLY_=true
is used (i.e. withou installed suggested packages):
* checking examples ... [5s] ERROR
Running examples …
```
=> Fix CRAN issue on suggested pkgs in CHECK

NEWS.md, R/docvars.R, cran-comments.md, man/docvars.Rd, tests/testthat/test-docvars.R, vignettes/quickstart.Rmd
Undoes the docvars() new arguments created in #2222, but restored that branch so that it can be merged into master.
Preserves some of the original PR, by removing docvars() for .readtext objects, and keeps a few other aspects that were tidied up.
=> Revert 2222

DESCRIPTION, NEWS.md, README.md, src/tokens_compound.cpp, tests/testthat/test-tokens_compound.R
We should update the v3.3 because it leads to a nasty crash.
=> Avoid segfault error when patterns have paddings in v3.3

src/tokens_compound.cpp, tests/testthat/test-tokens_compound.R
This does nothing do with recent changes. It is a very old bug.
=> Avoid segfault error when patterns have paddings

NEWS.md, R/quanteda_options.R, R/tokens.R, man/tokens.Rd
Makes word4 the new default, and eliminates the warning when additional arguments valid for "word4" are passed to `tokenize_word4()`. It does, however, not produce a warning message when other `what` values are used, so perhaps we should make the `check_dots()` conditional.
=> Switch tokenizer to word4

R/pattern2fixed.R, tests/testthat/test-pattern2fixed.R
This is a critical bug that leads `patter2fixed()` to ignore matching types `"<xxx>", "<xx.yy>"` when one of the types `<*>` is a the same as the glob pattern.
=> Fix pattern2fixed in v4

NEWS.md, R/tokens_group.R, man/head.dfm.Rd, src/RcppExports.cpp, src/tokens_group.cpp
Due to the double loop in the current code for `tokens_group()`, R almost freezes when the number of documents (sentences) are very large (ndoc > 10M).
=> Fix tokens group

src/index.cpp, src/tokens_chunk.cpp, src/tokens_compound.cpp, src/tokens_lookup.cpp, src/tokens_ngrams.cpp, src/tokens_replace.cpp, src/tokens_restore.cpp, src/tokens_segment.cpp, src/tokens_select.cpp
See https://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability-container-size-empty.html.
=> Use .empty() where appropriate

R/tokenizers.R, R/tokens.R, tests/testthat/test-tokens-word4.R
I noticed that the regex pattern induced in v.3.3 for `remove_url`  deletes acronyms.
```r
> tokens("the U.S. and Canada", remove_url = TRUE)
Tokens consisting of 1 document.
text1 :
[1] "the"    "."      "and"    "Canada"
```
The new pattern works like this, but I wonder if we want to remove email address. I so we need to updated the documentation.
```r
> txt <- c("The URL was http://t.co/something.",
+          "The URL was http://quanteda.io",
+          "https://github.com/quanteda/quanteda/issue/1 is another URL",
+          "www.r-project.org/about.html is a specific page without protocol",
+          "https://www.google.com/search?q=quanteda+package is a google search",
+          "ftp://user@host/foo/bar.txt is a FTP-hosted file",
+          "kohei.watanabe@quanteda.org is an …
```
=> Fix regex for remove_url

man/head.dfm.Rd, src/pattern2fixed.cpp, tests/testthat/test-pattern2fixed.R
This should not happen anymore
```
> pat <- stringi::stri_rand_strings(1000000, 1:10)
> type <- stringi::stri_rand_strings(1000000, 1:10)
> quanteda:::cpp_index_types(pat, type, FALSE)
Error: std::bad_alloc
```
=> Fix error in cpp_index_type when vectos for types and patters are very large

NEWS.md, R/corpus.R, man/corpus.Rd, man/head.dfm.Rd, tests/testthat/test-corpus.R
I added `concatenator` to `corpus.kwic()` as in #2118. It might be nice to use `lifecycle::expect_deprecated()` in other tests too.
=> Issue 2118

R/meta.R, R/tokens-methods.R, R/tokens.R, tests/testthat/test-tokens.R
Address #2313. We might want to drop `what` from the object meta fields because it is unreliable and redundant.
=> Save tokenizer

R/corpus_trim.R, R/tokens_ngrams.R, man/corpus_trim.Rd, tests/testthat/test-lifecycle-changes.R, tests/testthat/test-tokens_ngrams.R, tests/testthat/test-tokens_recompile.R
Deprecated `char_ngrams()` and remove `tokens()` from `corpus_trim()` for #2331.
=> Issue 2331

NEWS.md, R/RcppExports.R, R/nfunctions.R, R/tokens_xptr.R, man/head.dfm.Rd, man/ntoken.Rd, src/RcppExports.cpp, src/tokens_xptr.cpp, tests/testthat/test-nfunctions.R, tests/testthat/test-tokens_xptr.R
If `ntoken(x, remove_padding = TRUE)`, it returns the number of tokens ignoring paddings. The results are the same as `ntoken(tokens_remove(x, pattern = ""))` but much more efficient. This will be useful in showing the number of tokens removed in verbose messagess (#2329).
I kept `...` in `ntoken()` but I think the argument should be deprecated as it does not work in `ntoken.dfm()`. User should just run `ntoken(tokens(x))` if necessary. The documentation also says "... not used".
=> Add remove_padding to ntoken()

DESCRIPTION, inst/include/lib.h, inst/include/tokens.h, src/RcppExports.cpp, src/utility.cpp
RcppArmadillo is not used in **quanteda** (only used in **quanteda.textmodels**).
=> Remove RcppArmadillo

R/tokens_restore.R, src/tokens_compound.cpp, src/tokens_restore.cpp
`match("\uE001", letters)` returns `NA` when the special character is not found. This leads to error in conversion to `unsingned int` in C++.
=> Fix tokens restore

R/quanteda-package.R, cran-comments.md, man/quanteda-package.Rd
Fixed:
- Breaking documentation link in two .Rd files in the package **tosca** is now fixed on the **quanteda** side. `?quanteda` now finds 
```
?`quanteda-package`
```
- **tidytext** - We have not only informed the package maintainer that their use in a vignette of a function deprecated in v3 (released in 2021) is now defunct, but also we issued a PR to fix this (https://github.com/juliasilge/tidytext/pull/242).
- **RNewsflow** - We have not only informed the package maintainer that their use in a vignette of a function deprecated in v3 (released in 2021) is now defunct, but also we issued a PR to fix this (https://github.com/kasperwelbers/RNewsflow/pull/9).
=> Partial fixes for breaking revdeps in v4

configure, configure.ac
Re: https://github.com/quanteda/quanteda/issues/2364#issuecomment-2041454789, this PR adds support for `pkg-config` to `configure.ac`. If `pkg-config` is found and `tbb` is installed, it now proceeds to the viability test. If either `pkg-config` is not found, or `pkg-config` finds no `tbb`, no viability test is used and `tbb` is assumed not to be present.
=> add pkg-config to configure.ac

README.Rmd, _pkgdown.yml, vignettes/pkgdown/parallelisation.Rmd
As discussed in #2387, this PR adds information on parallelisation to README and a new article on parallelisation in **quanteda** >v4.0.0 for [quanteda.io](https://quanteda.io).
@kbenoit: thanks for reviewing, editing, and rebuilding the website and package.
=> Instructions on how to enable parallelisation

DESCRIPTION, NEWS.md, R/RcppExports.R, R/tokens_compound.R, inst/WORDLIST, man/tokens_compound.Rd, src/RcppExports.cpp, src/tokens_compound.cpp, src/tokens_replace.cpp, src/tokens_restore.cpp, tests/testthat/test-tokens_compound.R, tests/testthat/test-tokens_xptr.R
Add `keep_unigrams` as discussed in #2399. Compared to other arguments of the function like `join` the name is rather long, so it could be just `keep`.
=> Issue 2399

DESCRIPTION, inst/include/lib.h, inst/include/tokens.h, src/RcppExports.cpp, src/utility.cpp, tests/testthat/test-dfm_weight.R
We are not using RcppArmadillo anymore.
=> Remove armadillo

src/tokens_xptr.cpp
Closes #2406. I still think that this is a sanitizer issue, but if we can avoid confusing it, you don't have to argue with CRAN. 
Here `ListOf` (`Tokens`) is a very particular class. But given that `as_list` returns a `List` in the first place, there is no gain in transforming it into a `ListOf`. So keeping everything as a `List` seems to content UBSAN. Using the `rocker/r-devel-ubsan-clang` container, I see:
```bash
$ ASAN_OPTIONS=detect_leaks=0 RDscript -e 'remotes::install_github("Enchufa2/quanteda", ref="test")'
$ RDscript -e 'quanteda::as.tokens(list("test"))'
Tokens consisting of 1 document.
text1 :
[1] "test"
```
=> Fix UBSAN issue

NEWS.md, R/dfm_lookup.R, tests/testthat/test-dfm_lookup.R
This is a major bug initially reported on OS. This fix alone deserves CRAN update.
https://stackoverflow.com/questions/79045365/unexpected-behaviour-with-dfm-lookup-ordering-of-entries-affects-feature-frequ/79049020?noredirect=1#comment139383225_79049020
=> Address #2424

NEWS.md, src/tokens_combine.cpp
I noticed that `vector.insert()` is taking long time. This change will make the `c` operation on tokens significantly faster.
=> Stop using vector.insert()

NEWS.md, R/char_select.R, R/dfm_lookup.R, R/dfm_select.R, R/index.R, R/object2fixed.R, R/tokens_compound.R, R/tokens_lookup.R, R/tokens_replace.R, R/tokens_segment.R, R/tokens_select.R, man/object2id.Rd, tests/testthat/test-dfm_select.R, tests/testthat/test-object2fixed.R
Address #2400. This slightly changes the behaviour of `dfm_select()` when `phrase()` is applied to `pattern`. I think the new behaviour is more correct.
=> Replace remove_unigram with match_pattern
