quanteda/quanteda

tests/testthat/testToLower.R

I just realised I wrote this code and forgot to add it to my PR #94.
The code is very simple but it tests the main aspects of `toLower()`. I copy-pasted the Russian text from your assignment.

Add two simple unit tests for toLower

---

README.Rmd

Didn't regenerate README.md because I don't know the exact command used
to do so...

Fix typo in README.Rmd file.

---

src/ngrams.cpp

Fix minor typo

---

R/corpus.R
R/textfile.R

Standardize printing of corpus and corpusSource (fixes #135)

---

R/ngrams.R
tests/testthat/testNgrams.R

Diagnoses, but does not fix, #153

Add tests from Guthrie paper

---

tests/testthat/testNgrams.R

Add tests for ngrams.R

---

R/plots.R
man/plot.kwic.Rd
tests/testthat/testPlots.R

Add sort parameter to plot.kwic

---

.travis.yml

Add slack notification token

---

src/sequences.cpp

I spotted potential problems for Solaris. Sorry for doing PR again.

Bugfix 257

---

DESCRIPTION
src/Makevars
src/Makevars.win
tests/testthat/testFcm.R

Some configurations seems missing for applying RcppParallel.

add links in src/Makevars & src/Makevars.win

---

R/ngrams.R

Use stringi for character concatenation

---

R/RcppExports.R
R/textstat_dist.R
src/ManhattanParallel_qatd.cpp
src/RcppExports.cpp
tests/benchmarks/benchmark_textstat_dist.html
tests/testthat/test-textstat_dist.R

Add "manhattan" tests
Add "manhattan" benchmarks

Add parallal method for "manhattan" distance

---

R/tokens.R
R/tokens_select.R
tests/testthat/test-tokens_select.R

Add remapping for 0 = "" in tokens_hashed_recompile

---

tests/testthat/test-tokens_compound.R

Add tests for #240

---

R/dfm_compress.R

Fix typo in dfm_compress() example

---

R/dfm_select.R
tests/testthat/test-collocations.R
tests/testthat/test-dfm.R
tests/testthat/test-dfm_select.R

Add more tests regarding issue_430

---

R/tokens.R
tests/testthat/test-tokens.R

Coerce types to character vector

---

R/dfm-methods.R
man/dfm_select.Rd
tests/testthat/test-as.dfm.R
tests/testthat/test-textstat_dist.R

Fixes #590 (as.dfm behaviour with regard to dim names)
Adds tests

Issue 590 as.dfm dimnames

---

R/RcppExports.R
R/dfm_select.R
man/dfm_select.Rd
src/RcppExports.cpp
tests/testthat/test-bootstrap.R
tests/testthat/test-dfm_select.R

Restores dfm_select where features is a dfm to original behaviour.

Fix dfm select dfm

---

R/tokens.R

Issue an warning for unused arguments.

Solved #Issue 606

---

src/dist_mt.cpp
src/init.c

Registration fix

---

R/dfm_weight.R
tests/testthat/test-dfm.R
tests/testthat/test-dfm_weight.R

Update dfm_weight warning message for weights  …
Add tests
See https://stackoverflow.com/questions/44132313/can-the-anew-dictionary-be-used-for-sentiment-analysis-in-quanteda.

Update dfm_weight warning message for weights

---

R/collocations.R
R/convert.R
R/corpus-deprecated.R
R/corpus-methods-base.R
R/corpus_subset.R
R/dfm-print.R
R/dfm.R
R/dfm_lookup.R
R/dfm_select.R
R/dfm_trim.R
R/dictionaries-liwc_old.R
R/dictionaries.R
R/fcm-methods.R
R/fcm.R
R/kwic.R
R/sequences.R
R/similarity.R
R/textmodel_wordscores.R
R/textstat_dist.R
R/textstat_lexdiv.R
R/textstat_readability.R
R/textstat_simil.R
R/tokenize.R
R/tokenize_outtakes.R
R/tokens.R
R/tokens_lookup.R
R/tolower-misc.R

Did my best to replace all the `ifelse` I found that could clearly be replaced with `if` and `else`, namely, whenever it was clear that the length of the logical argument to `ifelse` was length-one.

Closes #764 -- replace ifelse with if/else where possible

---

DESCRIPTION
NEWS.md
R/RcppExports.R
R/textmodel_NB.R
src/RcppExports.cpp
tests/testthat/test-textmodel_NB.R

- textmodel_NB(x, y, distribution = "Bernoulli") previously had no effect - it was always multinomial.
- Fixes #776

Fix textmodel_NB with Bernoulli distribution

---

R/RcppExports.R
R/dfm_lookup.R
R/dfm_select.R
R/dictionaries.R
src/RcppExports.cpp
tests/testthat/test-dfm_lookup.R
tests/testthat/test-dfm_select.R

Add special handling of dictionary to dfm_select()

---

DESCRIPTION
NEWS.md
R/RcppExports.R
R/textmodel_NB.R
man/textmodel_NB.Rd
src/RcppExports.cpp
tests/testthat/test-textmodel_NB.R

Fixes #780.
- Fixes computation of likelihoods esp smoothing in fitting the model
- Fixes the prediction
- Matches Fig 13.3 in Manning Raghavan and Schutze IIR.

Fix broken textmodel_NB(x, distribution = "Bernoulli")

---

R/RcppExports.R
src/RcppExports.cpp
src/recompile.h

Fix variable declaration

---

src/quanteda.h
src/sequences_mt.cpp
src/tokens_compound_mt.cpp
tests/testthat/test-textstat_collocations.R

Hotfix 831

---

R/RcppExports.R
R/zzz.R
src/RcppExports.cpp
src/init.c
src/quanteda.h
src/utility.cpp

Add function to check if TBB is enabled, and fix misleading start-up message.

Dev tbb enabled

---

DESCRIPTION
NEWS.md
R/RcppExports.R
R/dfm.R
R/quanteda_options.R
src/RcppExports.cpp
tests/testthat/test-quanteda_options.R

Fix problem when functions are called without package being loaded

---

R/RcppExports.R
R/textplot_keyness.R
R/textstat_keyness.R
man/keyness.Rd
man/textplot_keyness.Rd
man/textstat_keyness.Rd
src/RcppExports.cpp
tests/testthat/test-textstat_keyness.R

Added Yates correction and min_count to testplot_keyness

---

R/dfm.R
R/textmodel_wordscores.R
R/tokens.R
R/wordstem.R

Use string instead of grep() and gsub() except in code that will be moved soon.

issue #507

---

R/textmodel_wordshoal.R
man/textmodel_wordshoal.Rd

Change occurrences of `ie30corpus` to `data_corpus_irish30` – otherwise the example cannot be executed.

Change in example for textmodel_wordshoal.R

---

R/textstat_dist.R
R/textstat_simil.R
man/textstat_simil.Rd

- Fixes #759 
@thomasd2 might be worth taking a look to see if this meets the standard of what you'd wanted.

Improve textstat_simil documentation

---

R/textmodel_wordfish.R
man/textmodel_wordfish.Rd
src/wordfish_mt.cpp

Added note and warning message for issue #757

solve Issue #757

---

src/wordfish_mt.cpp

pretty obvious why this should be done

change int -> size_t in one for loop

---

DESCRIPTION
NEWS.md
R/textstat_collocations.R
tests/testthat/test-textstat_collocations.R

Fix #940, textstat_collocations.tokens() when a document is all ""

---

vignettes/pkgdown_only/plotting.Rmd

- Use texstat_frequency() instead of topfeatures()
- Remove depreciated commands
- Add plot with most frequent words in terms of relative frequency by group
- Remove reference to GitHub version (not necessary anymore as all required commands are on CRAN)

Update plotting vignette

---

DESCRIPTION
NEWS.md
R/dfm_weight.R
man/tfidf.Rd
tests/testthat/test-dfm_weight.R

Clarifies the computation of tfidf and compares this to how the **tm** package computes it.
Solves #997.

Improve tfidf documentation

---

tests/testthat/test-tokens.R

Prepare for the release of testthat 2.0  #1025

expect_equivalent will not take multiple test objects

---

R/dfm-print.R
R/fcm.R
R/quanteda_options.R
R/textstat_dist.R
R/tokens_ngrams.R
man/head.dfm.Rd
man/print.dfm.Rd
man/quanteda_options.Rd
tests/testthat/test-dfm.R
tests/testthat/test-quanteda_options.R
tests/testthat/test-textstat_dist.R
tests/testthat/test-tokens_ngrams.R

Fix #1110.
Changes `nfeature` arguments to `feat`.

Solve issue 1110

---

vignettes/pkgdown/examples/quickstart_cn.Rmd

Changed the link to quickstart.Rmd and chinese.Rmd.

Fix issue #1131

---

DESCRIPTION
NEWS.md
R/dfm_weight.R
tests/testthat/test-dfm_weight.R

Fix #1150, bug for named weights in dfm_weight()

---

R/dfm_weight.R
R/fcm.R
tests/testthat/test-dfm_weight.R
tests/testthat/test-fcm.R

Not only address 1150, but also make fcm more robust

Issue 1150

---

DESCRIPTION
NEWS.md
R/textplot_network.R
man/textplot_network.Rd
tests/testthat/test-textplot.R

add option family to textplot_network

---

R/textstat_dist.R
R/textstat_simil.R
tests/testthat/test-textstat_dist.R
tests/testthat/test-textstat_simil.R

Make dist and simil robust against seletion with padding

---

DESCRIPTION
R/textplot_network.R
tests/testthat/test-textplot.R

Adds check for available fonts. Works on Windows and Linux, but not sure about Mac. @amatsuo , can you check on you system?

Issue 1179

---

vignettes/design.Rmd

Changed `remove_numers` to `remove_numbers`

fixed typo in vignettes/design.Rmd

---

docs/articles/pkgdown/replication/qss.html
vignettes/pkgdown/replication/qss.Rmd

The "unknown" texts were not plotted in the previous version.

Fix plotting issue in qss vignette

---

R/dictionaries.R

Add check if list is empty to address #1309

---

R/corpus-methods-base.R
R/corpus_segment.R
man/corpus_segment.Rd
man/summary.corpus.Rd

These don't affect the code, but I wanted to check with you @koheiw re the new pkgdown updating workflow before I merged them into master. These _should_ update to the pkgdown site, but only these.

Minor documentation typo fixes

---

R/textplot_scale1d.R
man/textplot_scale1d.Rd
vignettes/pkgdown/examples/plotting.Rmd

Issue 1340

---

DESCRIPTION
README.Rmd
README.md

Put my first name and last name in correct order

Update my name

---

R/textplot_keyness.R
R/utils.R

Set base_family to allow users to change legend font address #1345

Issue 1345

---

DESCRIPTION
LICENSE
R/data-documentation.R
R/utils.R
inst/CITATION
man/data_corpus_dailnoconf1991.Rd
man/friendly_class_undefined_message.Rd
man/quanteda-package.Rd

Fix some CRAN issues detailed in #1350.

Issue 1350

---

DESCRIPTION
NEWS.md
R/corpus.R
tests/testthat/test-corpus.R
tests/testthat/test-kwic.R
tests/testthat/test-tokens.R

- Substitute NA with empty string in corpus constructor to address #1372 
- Change test expectations

 Handle NA document properly 

---

R/textplot_network.R

Use theme_void() to remove border #1382

---

R/tokens.R
tests/testthat/test-tokens.R

- Disallow combining tokens with different concatenate or what values
- Join and sort ngrams or skip values

Add attributes to tokens object after combining

---

R/corpus_reshape.R
R/corpus_segment.R
R/tokens_ngrams.R
man/corpus_segment.Rd
tests/benchmarks/benchmark_tokens/ngrams.R
tests/testthat/test-corpus_reshape.R
tests/testthat/test-corpus_segment.R

Address #1394
- Reimplement pattern extraction to support multiple fixed patterns
- Add case insensitive option

Issue 1394

---

R/dfm-classes.R

See diff ;-) The code suggestion should be fit for copy-pasting, I assume.

Repair alternative code suggestion in deprecation warning

---

DESCRIPTION
NEWS.md
R/RcppExports.R
R/kwic.R
man/kwic.Rd
man/unused_dots.Rd
src/RcppExports.cpp
src/kwic_mt.cpp
tests/testthat/test-kwic.R

For #1449. I need this to be merged to upgrade `corpus.kwic()` in the dev-corpus2 branch.

Add separator argument for #1449

---

R/textstat_dist_old.R
R/textstat_simil.R
man/textstat_proxy.Rd
tests/testthat/test-textstat_proxy.R

This branch removes performance penalty by column compression to mitigate  #1469.
Closes #1469.

Speed up conversion to dist object for #1469

---

tests/testthat/test-textstat_proxy.R

Update test for explicit zeros

---

R/RcppExports.R
R/textstat_simil.R
man/textstat_proxy.Rd
src/RcppExports.cpp
src/simil_mt.cpp
tests/testthat/test-textstat_proxy.R
tests/testthat/test-textstat_simil.R
tests/testthat/test-utils.R

Dev textstat proxy

---

R/dictionaries.R
man/as.dictionary.Rd
man/dictionary-class.Rd
tests/testthat/test-as.dictionary.R

Fix issue #1562

---

R/quanteda_options.R
tests/testthat/test-quanteda_options.R

Set OMP_THREAD_LIMIT with value checks

---

R/tokens_replace.R

to address issues such as https://stackoverflow.com/questions/54786317/tokens-replace-only-works-with-stri-trans-general-and-not-with-encoding

Add Unicode normalization to tokens_replace()

---

R/tokens_compound.R
R/utils.R
inst/WORDLIST
man/tokens_compound.Rd
tests/testthat/test-kwic.R
tests/testthat/test-tokens_compound.R

Enable case-insensitive argument even when pattern is collocations

---

src/fcm_mt.cpp
src/kwic_mt.cpp
src/quanteda.h
src/tokens_chunk_mt.cpp
src/tokens_segment_mt.cpp

Qualified std member access in fcm_mt.cpp, kwic_mt.cpp, tokens_chunk_mt.cpp, tokens_segment_mt.cpp

Removed global std namespace usage from quanteda.h

---

R/corpus.R

Add Unicode normalization

---

R/tokens_ngrams.R
man/tokens_ngrams.Rd
tests/testthat/test-dfm_sample.R

Solves #1658 
Verified on r-hub builder for Debian Linux, R-devel, GCC.

Fixes dfm_sample and a broken URL CRAN errors

---

DESCRIPTION
NEWS.md
R/dictionaries.R
docs/articles/design.Rmd
docs/articles/pkgdown/examples/plotting.Rmd
index.Rmd
man/dictionary-class.Rd
tests/testthat/test-dictionaries.R
vignettes/pkgdown/examples/twitter.Rmd
vignettes/pkgdown/replication/digital-humanities.Rmd
vignettes/pkgdown/replication/qss.Rmd

Add flatten and levels to as.list.dictionary2

---

R/dictionaries.R
tests/testthat/test-dictionaries.R

Improve value check to address #1668

---

R/textstat_frequency.R
man/textstat_frequency.Rd

Issue 1671

---

DESCRIPTION
NEWS.md
R/kwic.R
tests/testthat/test-kwic.R

Make behaviour of kwic.corpus() and kwic.tokens() identical

---

R/dfm_weight.R

#1703 
```r
mat <- Matrix::rsparsematrix(1e6, 100000, density = 0.0001)
w <- rnorm(100000)
mat %*% Matrix::Diagonal(x = w) # works 
mat %*% diag(w) # does not work
```

Use diagonal matrix in Matrix

---

R/textstat_simil.R
tests/testthat/test-textstat_proxy.R
tests/testthat/test-textstat_simil.R

Set NA for empty documents/features

---

NEWS.md
R/textstat_readability.R
inst/WORDLIST
man/textstat_readability.Rd
tests/testthat/test-textstat_readability.R

Add default measure for readability, fix DRP/Bormuth

---

R/RcppExports.R
R/fcm-methods.R
R/fcm.R
man/fcm.Rd
src/RcppExports.cpp
src/fcm_mt.cpp
tests/testthat/test-as.dictionary.R
tests/testthat/test-fcm.R

I fully inspected the code for #1461, and made changes where improvement is possible.

Issue 1461

---

DESCRIPTION
NEWS.md
NOTES.md
R/textstat_simil.R
tests/testthat/test-textstat_simil.R

Improve assignment of NA

---

R/textmodel_nb.R
tests/testthat/test-textmodel_nb.R

Require y to be non-constant in textmodel_nb()

---

R/nfunctions.R
tests/testthat/test-nfunctions.R
tests/testthat/test-textmodel_nb.R

Implement ... passing in ntokens/ntype.tokens

---

R/fcm-methods.R
R/fcm.R
tests/testthat/test-fcm.R

Issue 1763

---

DESCRIPTION
NEWS.md
R/convert.R
man/convert.Rd
tests/testthat/test-convert.R

Add corpus conversion method to output json. A simple convenience wrapper.

Convert corpus json

---

R/dfm.R
R/dfm_lookup.R
R/dfm_select.R
tests/testthat/test-dfm.R
tests/testthat/test-dfm_sample.R
tests/testthat/test-dfm_select.R
tests/testthat/test-fcm_methods.R

Issue 1807

---

R/corpus_sample.R
R/corpus_subset.R
tests/testthat/test-corpus_sample.R

- fixes #1813
- (hopefully) addresses https://github.com/sborms/sentometrics/issues/8#issuecomment-562570828

Sample and subset corpus using []

---

R/corpus-methods-base.R
R/tokens-methods-base.R
tests/testthat/test-corpus.R
tests/testthat/test-tokens.R

Fix negative indexing using a dummy named-numeric vector #1830

Issue 1830

---

R/corpus-methods-base.R
R/corpus.R
R/utils.R
tests/testthat/test-corpus.R
tests/testthat/test-summary.R

Fix c.corpus

---

R/tokens-methods-base.R
R/tokens.R
tests/testthat/test-tokens.R

Fix c.tokens

---

R/dfm-methods.R
tests/testthat/test-as.dfm.R

Small but important fix for #1885

Set dimension of DTM and TDM for empty documents

---

R/object-builder.R
tests/testthat/test-object-builders.R

Address an issue surfaced in #1884

Add R's base class to corpus

---

R/corpus.R
tests/testthat/test-corpus.R
tests/testthat/test-dfm_group.R

For #1889. Hope that we can include this in v2.0.

Normalize dashes and hyphens

---

R/tokens_replace.R
tests/testthat/test-tokens_replace.R

Fix for no match and add tests

---

R/dfm-print.R
tests/testthat/test-dfm.R

Do not print matrix when ndoc = 0 or nfeat = 0

---

NEWS.md
R/tokens.R
tests/testthat/test-tokens.R

We have a long, clever regex to get the cases in the added test, but it didn't cover plain numbers of 10000 or over!!
Solves #1909

Fix number regex to solve #1909

---

NEWS.md
R/textstat_frequency.R
tests/testthat/test-textstat_frequency.R

Don't return NA for non-existent features when n > nfeat(x)

---

R/textstat_simil.R
tests/testthat/test-textstat_simil.R

Fix document2 labels in subsetted as.data.frame.textstat_proxy()

---

R/docvars.R
tests/testthat/test-dfm_group.R
tests/testthat/test-tokens_group.R

Issue 1949

---

NEWS.md
R/RcppExports.R
R/kwic.R
R/textplot_xray.R
man/textplot_xray.Rd
src/RcppExports.cpp
src/kwic_mt.cpp

Remove really slow R loop to partially solve #1840 
```r
> corp <- as.corpus(quanteda.corpora::download("data_corpus_guardian"))
> toks <- tokens(corp)
> system.time(
+     kw <- kwic(toks, stopwords("en"))
+ )
user  system elapsed 
26.002   0.354  18.945
```
But string creation is still the slowest part in C++, so need to be addressed more fundamentally.
```
'Search keywords'    3290.42 millsec
'Create strings'     14559 millsec
'Create data.frame'  33.7481 millsec
```

Issue 1840

---

R/dictionaries.R
man/flatten_dictionary.Rd

I'm not even sure how this passed the checks in the first place!

Fix mismatch in documentation v function parameters

---

R/dictionaries.R
man/dictionary.Rd
man/read_dict_functions.Rd
man/valuetype.Rd
tests/testthat/test-dictionaries.R

Remove auto-detection of dictionary encoding

---

R/textstat_collocations.R
R/textstat_keyness.R
R/utils.R
tests/testthat/test-cache.R
tests/testthat/test-textstat_summary.R

Address the issue of randomly failing tests on different platforms.

Fix sorting

---

tests/testthat/test-index.R
tests/testthat/test-kwic.R

Fix old-release broken tests

---

R/quanteda_options.R
cran-comments.md
man/quanteda_options.Rd
tests/testthat/test-quanteda_options.R

Fixes warning that occurs on Debian devel

---

NEWS.md
R/dfm-classes.R
tests/testthat/test-docvars.R

Keep docvars in rbind.dfm

---

DESCRIPTION
NEWS.md
R/dfm.R
R/dfm_lookup.R
R/tokens_lookup.R
tests/testthat/test-dfm.R
tests/testthat/test-dfm_lookup.R
tests/testthat/test-tokens_lookup.R

Sort the columns of DFM to address #2100.

Sort DFM columns

---

DESCRIPTION
NEWS.md
R/tokens.R
man/tokenize_internal.Rd
man/tokens.Rd
tests/testthat/test-tokens.R
tests/testthat/test-tokens_ngrams.R
tests/testthat/test-tokens_recompile.R

Address #2156. We cannot disable the internet address matching, but hope that it does not have huge impact on speed in any case.
https://github.com/quanteda/quanteda/blob/353bfe36d015705e33d534a5d85163b2b8c5c666/R/tokenizers.R#L62-L64

Add split_tags to tokens()

---

NEWS.md
R/dfm_lookup.R
R/object2fixed.R
man/object2id.Rd
tests/testthat/test-dfm_lookup.R

Mainly to address #2159 but I fixed a bug in multiple matches in `exclusive  = FALSE` (the second case in the added test). You might want to add more tests.

Issue 2159

---

NEWS.md
R/fcm.R
tests/testthat/test-fcm.R

Issue 2176

---

R/pattern2fixed.R
tests/testthat/test-pattern2fixed.R

Fix pattern2fixed in v3

---

README.Rmd
README.md

Fix typos and formatting issues in README

Fix readme

---

R/tokens-methods.R
src/tokens_group.cpp
tests/testthat/test-tokens.R

Issue 2299

---

R/dfm_trim.R
man/dfm_trim.Rd

Improve dfm_trim documentation for #2200

---

NEWS.md
R/corpus_subset.R
R/dfm_subset.R
R/tokens_subset.R
R/tokens_xptr.R
man/corpus_subset.Rd
man/dfm_subset.Rd
man/tokens_subset.Rd
tests/testthat/test-dfm_subset.R
tests/testthat/test-tokens_subset.R
tests/testthat/test-tokens_xptr.R

I think adding `min_ntoken` and `max_ntoken` is the best solution to #2237

Add min_ntoken and max_ntoken

---

NEWS.md
R/dfm-methods.R
man/head.dfm.Rd
tests/testthat/test-dfm.R

Disable topfeatures.fcm()

---

README.Rmd

Please review and rebuild **pkgdown** website if you're happy with the changes, @kbenoit.

Fix formatting of list and add link to cheatsheet

---

R/RcppExports.R
R/kwic.R
src/RcppExports.cpp
src/index.cpp
src/kwic.cpp
src/pattern2fixed.cpp
src/utf8.h
tests/testthat/test-kwic.R
tests/testthat/test-tokens_xptr.R

Dev cpp kwic

---

R/data-documentation.R
R/quanteda-documentation.R
R/tokens.R
man/data_dictionary_LSD2015.Rd
man/pattern.Rd
man/tokens.Rd
man/valuetype.Rd

Discovered while teaching a short course on text analysis and quanteda.

Minor documentation fixes

---

DESCRIPTION
inst/include/lib.h
inst/include/tokens.h
man/tokens_wordstem.Rd
src/RcppExports.cpp
src/utility.cpp

Reverts quanteda/quanteda#2353 because it causes too many problems in dependent packages.

Revert "Remove RcppArmadillo"

---

R/tokens.R
man/tokens_recompile.Rd

Stops warnings for unused arguments.

Remove unused arguments

---

R/quanteda-documentation.R
R/textstat.R
man/is.collocations.Rd
man/quanteda-package.Rd

Remove Rd xrefs to quanteda.textstats

---

inst/include/lib.h

I could come up with this only fix for #2406.

Replace range constructor with wrap()

---

R/nfunctions.R
src/tokens_xptr.cpp
tests/testthat/test-nfunctions.R

Fix ntype.tokens()

---

R/tokenizers.R
R/tokens.R
tests/testthat/test-tokens-word4.R

Implements new URL regex and tries tests ... which are currently failing for extended URLs.

Implement issue 2430

---

DESCRIPTION
NEWS.md
R/tokens_compound.R
tests/testthat/test-tokens-word4.R
tests/testthat/test-tokens.R
tests/testthat/test-tokens_compound.R

Issue 2432

---

R/char_select.R
tests/testthat/test-char_select.R

For breaking tests in #2444 #2445

Simplify handling of patterns in char_select()

---

R/bootstrap_dfm.R
man/bootstrap_dfm.Rd
tests/testthat/test-bootstrap.R

Issue 2425

---

NEWS.md
R/RcppExports.R
R/tokens_ngrams.R
man/tokens_ngrams.Rd
src/RcppExports.cpp
src/tokens_ngrams.cpp
tests/testthat/test-tokens_ngrams.R

Add apply_if tokens_ngrams()

---

DESCRIPTION
NEWS.md
R/wordstem.R
cran-comments.md
inst/include/lib.h
man/convert.Rd
man/tokens_wordstem.Rd
src/tokens_xptr.cpp
tests/spelling.R
tests/testthat/test-object2fixed.R
tests/testthat/test-spelling.R

Tidies up a few things such as a change in test behaviour related to one straight v curly quote issue, fixes a few URLs, increments the quanteda version, and attempts a fix at the clang-UBSAN issues currently listed on CRAN. @koheiw please review the latter especially.

R 4.5 fixes
